function createfigure(ZData1, YData1, XData1, ZData2, YData2, XData2, ZData3, YData3, XData3, ZData4, YData4, XData4, YData5, YData6, XData5, XData6)
%CREATEFIGURE(ZData1, YData1, XData1, ZData2, YData2, XData2, ZData3, YData3, XData3, ZData4, YData4, XData4, YData5, YData6, XData5, XData6)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  ZDATA2:  surface zdata
%  YDATA2:  surface ydata
%  XDATA2:  surface xdata
%  ZDATA3:  surface zdata
%  YDATA3:  surface ydata
%  XDATA3:  surface xdata
%  ZDATA4:  surface zdata
%  YDATA4:  surface ydata
%  XDATA4:  surface xdata
%  YDATA5:  surface ydata
%  YDATA6:  surface ydata
%  XDATA5:  surface xdata
%  XDATA6:  surface xdata

%  Auto-generated by MATLAB on 12-May-2022 08:40:43

% Create figure
figure1 = figure('Color',[0 0 0]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surface
surface('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
    'MarkerFaceColor',[0 0 1],...
    'MarkerSize',4,...
    'Marker','>',...
    'LineStyle','--',...
    'FaceColor',[0 0 1],...
    'EdgeColor',[0 1 0],...
    'CData',ZData1);

% Create hgtransform
hgtransform1 = hgtransform('Parent',axes1);

% Create surface
surface('Parent',hgtransform1,'ZData',ZData2,'YData',YData2,'XData',XData2,...
    'Clipping','off',...
    'CData',ZData2);

% Create surface
surface('Parent',hgtransform1,'ZData',ZData3,'YData',YData3,'XData',XData3,...
    'Clipping','off',...
    'CData',ZData3);

% Create surface
surface('Parent',hgtransform1,'ZData',ZData4,'YData',YData4,'XData',XData4,...
    'Clipping','off',...
    'FaceColor',[1 0 0],...
    'CData',ZData4);

% Create surface
surface('Parent',hgtransform1,'ZData',ZData4,'YData',YData5,'XData',XData4,...
    'Clipping','off',...
    'FaceColor',[1 0 0],...
    'CData',ZData4);

% Create surface
surface('Parent',hgtransform1,'ZData',ZData4,'YData',YData6,'XData',XData5,...
    'Clipping','off',...
    'FaceColor',[1 0 0],...
    'CData',ZData4);

% Create surface
surface('Parent',hgtransform1,'ZData',ZData4,'YData',YData6,'XData',XData6,...
    'Clipping','off',...
    'FaceColor',[1 0 0],...
    'CData',ZData4);

view(axes1,[-37.5 30]);
box(axes1,'on');
grid(axes1,'on');
axis(axes1,'tight');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Color',[0 0 0],'DataAspectRatio',[1 1 1],'XColor',[0 1 0],...
    'YColor',[0 1 0],'ZColor',[0 1 0]);
