function createfigure1(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 05-May-2022 01:38:50

% Create figure
figure1 = figure('Color',[0 0 0]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'LineWidth',2);

% Create ylabel
ylabel('Mass(kg)','BackgroundColor',[0 0 0],'EdgeColor',[1 0 0],...
    'HorizontalAlignment','center',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('Time(s)','BackgroundColor',[0 0 0],'EdgeColor',[1 0 0],...
    'HorizontalAlignment','center',...
    'Color',[1 0 0]);

% Create title
title('Mass vs Time)','BackgroundColor',[1 0 0],...
    'HorizontalAlignment','center',...
    'FontWeight','bold');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'Color',[0 0 0],'XColor',[0 1 0],'YColor',[0 1 0],'ZColor',...
    [0 1 0]);
